### PR TITLE
Trim "topic" from predefined topic method names

### LINKED ISSUE #16: Shorten method names of subscribe/unsubscribe to a predefined topic
A term "topic" in `SubscribePredefinedTopic` and `UnsubscribePredefinedTopic` seems redundant. Prefer the shorter versions:

* `SubscribePredefined`
* `UnsubscribePredefined`

### PR DESCRIPTION
**Pull request by besedad**
Closes #16.

### CODE REVIEW

**Review by mprymek — APPROVED** [review]
LGTM.

Just a suggestion: don't you want to do the same thing in `client/` before bumping the version?

**Comment by besedad** [comment]
> Just a suggestion: don't you want to do the same thing in client/ before bumping the version?

What do you mean? This is changing the forward facing API in the client.

**Comment by mprymek** [comment]
> > Just a suggestion: don't you want to do the same thing in client/ before bumping the version?
> 
> What do you mean? This is changing the front facing API in the client.

There's `SubscribePredefinedTopic` (and probably more) in `client/`. You could strip `Topic` there also (in this PR) and bump version after that. But I don't Insist on it. It was just a suggestion.

**Comment by mprymek** [comment]
> > Just a suggestion: don't you want to do the same thing in client/ before bumping the version?
> 
> What do you mean? This is changing the front facing API in the client.

I'm sorry, I was looking at wrong branch files :) Forget that...

**Pull request merged**
